import sqlite3
import logging
from typing import Optional

# Setup basic logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

def init_db(db_path: str = "agent_memory.db") -> None:
    """
    Initializes the SQLite database with the necessary schema.
    Creates the 'sessions' and 'turns' tables if they do not exist.
    
    Args:
        db_path: The path to the SQLite database file.
    """
    schema = '''
    CREATE TABLE IF NOT EXISTS sessions (
        session_id TEXT PRIMARY KEY,
        goal TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS turns (
        turn_id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL,
        thought TEXT NOT NULL,
        action TEXT NOT NULL,
        action_input TEXT NOT NULL,
        observation TEXT NOT NULL,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(session_id) REFERENCES sessions(session_id)
    );

    CREATE TABLE IF NOT EXISTS turn_metrics (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT NOT NULL,
        user_query TEXT NOT NULL,
        search_queries TEXT,
        urls_opened TEXT,
        context_snippets TEXT,
        final_answer TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(session_id) REFERENCES sessions(session_id)
    );
    '''
    
    try:
        # Context manager ensures connection is closed automatically when leaving the block
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            cursor.executescript(schema)
            conn.commit()
            logger.info(f"Database initialized successfully at '{db_path}'.")
    except sqlite3.Error as e:
        logger.error(f"Failed to initialize database: {e}")
        raise

def create_session(session_id: str, goal: str, db_path: str = "agent_memory.db") -> bool:
    """
    Creates a new research session in the database.
    
    Args:
        session_id: A unique identifier for the session.
        goal: The initial research goal or prompt.
        db_path: The path to the SQLite database file.
        
    Returns:
        bool: True if creation was successful, False otherwise.
    """
    query = "INSERT OR IGNORE INTO sessions (session_id, goal) VALUES (?, ?)"
    try:
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(query, (session_id, goal))
            conn.commit()
            return True
    except sqlite3.Error as e:
        logger.error(f"Failed to create session '{session_id}': {e}")
        return False

def record_turn(session_id: str, thought: str, action: str, action_input: str, observation: str, db_path: str = "agent_memory.db") -> Optional[int]:
    """
    Records a single agent turn into the database.
    
    Args:
        session_id: The identifier of the active session.
        thought: The internal reasoning of the agent.
        action: The action taken by the agent.
        action_input: The input provided to the action.
        observation: The result returned by the action.
        db_path: The path to the SQLite database file.
        
    Returns:
        Optional[int]: The turn_id of the inserted record if successful, None otherwise.
    """
    query = """
    INSERT INTO turns (session_id, thought, action, action_input, observation) 
    VALUES (?, ?, ?, ?, ?)
    """
    try:
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(query, (session_id, thought, action, action_input, observation))
            conn.commit()
            return cursor.lastrowid
    except sqlite3.Error as e:
        logger.error(f"Failed to record turn for session '{session_id}': {e}")
        return None

def record_turn_metrics(session_id: str, user_query: str, search_queries: str, urls_opened: str, context_snippets: str, final_answer: str, db_path: str = "agent_memory.db") -> Optional[int]:
    """
    Records detailed metrics for a single user query cycle.
    
    Args:
        session_id: The identifier of the active session.
        user_query: The exact user query.
        search_queries: The search queries issued by the agent.
        urls_opened: Comma-separated list of URLs opened.
        context_snippets: The context blocks selected for the LLM.
        final_answer: The final response generated by the agent.
        db_path: The path to the SQLite database file.
        
    Returns:
        Optional[int]: The id of the inserted record if successful, None otherwise.
    """
    query = """
    INSERT INTO turn_metrics (session_id, user_query, search_queries, urls_opened, context_snippets, final_answer) 
    VALUES (?, ?, ?, ?, ?, ?)
    """
    try:
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(query, (session_id, user_query, search_queries, urls_opened, context_snippets, final_answer))
            conn.commit()
            return cursor.lastrowid
    except sqlite3.Error as e:
        logger.error(f"Failed to record turn metrics for session '{session_id}': {e}")
        return None

def get_chat_history(session_id: str, db_path: str = "agent_memory.db") -> list:
    """
    Reconstructs the chat history for a given session by extracting user queries
    and agent responses from the turn_metrics logs.
    
    Args:
        session_id: The session identifier.
        db_path: Path to the SQLite database.
        
    Returns:
        list: A list of dicts formatted as [{"query": "...", "response": "...", "citations": [...], "steps": [...]}, ...]
    """
    query = """
    SELECT user_query, final_answer, urls_opened, search_queries
    FROM turn_metrics 
    WHERE session_id = ? 
    ORDER BY id ASC
    """
    history = []
    try:
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(query, (session_id,))
            rows = cursor.fetchall()
            
            for user_query, final_answer, urls_opened, search_queries in rows:
                citations = []
                if urls_opened:
                    urls = [u.strip() for u in urls_opened.split(",") if u.strip()]
                    for i, url in enumerate(urls):
                        domain = url.split("//")[-1].split("/")[0]
                        citations.append({"url": url, "domain": domain, "title": f"Source {i+1}"})
                
                steps = []
                if search_queries:
                    steps.append("Searching the web for information...")
                    steps.append(f"Queries executed: {search_queries}")
                    steps.append("Analysing content and synthesizing response...")

                history.append({
                    "query": user_query, 
                    "response": final_answer,
                    "citations": citations,
                    "steps": steps
                })
                        
            return history
    except sqlite3.Error as e:
        logger.error(f"Failed to fetch history for session '{session_id}': {e}")
        return []

def delete_session(session_id: str, db_path: str = "agent_memory.db") -> bool:
    """
    Deletes all records associated with a specific session ID.
    
    Args:
        session_id: The session identifier to delete.
        db_path: Path to the SQLite database.
        
    Returns:
        bool: True if successful, False otherwise.
    """
    query = "DELETE FROM turn_metrics WHERE session_id = ?"
    try:
        with sqlite3.connect(db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(query, (session_id,))
            conn.commit()
            return cursor.rowcount > 0
    except sqlite3.Error as e:
        logger.error(f"Failed to delete session '{session_id}': {e}")
        return False
